version: '2.1'

networks:
    proxy:
        external:
            name: common_proxy

services:
    pythondjango_db:
        container_name: pythondjango_db
        image: 'postgres:11.1'
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=docker
        ports:
            - '5433:5432'
        volumes:
            # - ./db.sql:/docker-entrypoint-initdb.d/db.sql
            - ./dbdata:/var/lib/postgresql/data/:delegated
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U docker']
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - proxy

    pythondjango_api:
        container_name: pythondjango_api
        build:
            context: ../api
            dockerfile: ../docker/dockerfiles/api
        volumes:
            - ../api:/code:delegated
        depends_on:
            pythondjango_db:
                condition: service_healthy
        networks:
            - proxy
        # command: bash -c "python manage.py migrate && gunicorn core.wsgi -b 0.0.0.0:8001"
        tty: true

    pythondjango_client:
        container_name: pythondjango_client
        build:
            context: ../client
            dockerfile: ../docker/dockerfiles/client
        working_dir: /code
        ports:
            - '3000:3000'
        volumes:
            - ../client:/code:delegated
            - /code/node_modules
        networks:
            - proxy
        tty: true
